# Generated by Django 2.0.4 on 2018-05-09 22:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shape_stle', models.FloatField(verbose_name='shape style')),
                ('dist_name', models.TextField(verbose_name='district name')),
                ('shape_star', models.FloatField(verbose_name='shape star')),
                ('district_i', models.FloatField(verbose_name='district ID')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
