# Generated by Django 2.0.4 on 2018-05-10 05:38

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_models_for_geo_districts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='dist_name',
        ),
        migrations.RemoveField(
            model_name='area',
            name='district_i',
        ),
        migrations.RemoveField(
            model_name='area',
            name='shape_star',
        ),
        migrations.RemoveField(
            model_name='area',
            name='shape_stle',
        ),
        migrations.AddField(
            model_name='area',
            name='extra_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
