# Generated by Django 2.0.4 on 2018-05-10 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_json_field_for_custom_shapefile_layer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='districts.District'),
        ),
    ]
