# Generated by Django 2.0.4 on 2018-09-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0003_null_district_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='district',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
