# Generated by Django 2.0.4 on 2018-09-17 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0004_areas_belong_to_offices_not_districts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='shape_file_name',
        ),
    ]
