# Generated by Django 2.0.4 on 2018-09-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_offices_and_candidates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('office__district', 'office', 'name')},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ('district', 'name')},
        ),
        migrations.AddField(
            model_name='office',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='offices.Office'),
        ),
        migrations.AlterField(
            model_name='office',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='districts.District'),
        ),
    ]
