# Generated by Django 2.0.4 on 2018-09-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_areas_belong_to_offices_not_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='shape_file_name',
            field=models.TextField(null=True),
        ),
    ]
